---
_type: document
_meta:
  url: http://localhost:8000/schema/
  title: ProcessEngine
process:
  list:
    _type: link
    url: "/process/"
    action: get
  create:
    _type: link
    url: "/process/"
    action: post
    encoding: application/json
    fields:
    - name: owners
      location: form
      schema:
        _type: array
        title: Owners
        description: object keys for objects that are allowed to act on this process
    - name: object_ids
      location: form
      schema:
        _type: array
        title: Object ids
        description: ''
    - name: payload
      location: form
      schema:
        _type: string
        title: Payload
        description: ''
    - name: definition
      location: form
      schema:
        _type: integer
        title: Definition
        description: ''
  read:
    _type: link
    url: "/process/{id}/"
    action: get
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this process.
  update:
    _type: link
    url: "/process/{id}/"
    action: put
    encoding: application/json
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this process.
    - name: owners
      location: form
      schema:
        _type: array
        title: Owners
        description: object keys for objects that are allowed to act on this process
    - name: object_ids
      location: form
      schema:
        _type: array
        title: Object ids
        description: ''
    - name: payload
      location: form
      schema:
        _type: string
        title: Payload
        description: ''
    - name: definition
      location: form
      schema:
        _type: integer
        title: Definition
        description: ''
  partial_update:
    _type: link
    url: "/process/{id}/"
    action: patch
    encoding: application/json
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this process.
    - name: owners
      location: form
      schema:
        _type: array
        title: Owners
        description: object keys for objects that are allowed to act on this process
    - name: object_ids
      location: form
      schema:
        _type: array
        title: Object ids
        description: ''
    - name: payload
      location: form
      schema:
        _type: string
        title: Payload
        description: ''
    - name: definition
      location: form
      schema:
        _type: integer
        title: Definition
        description: ''
  delete:
    _type: link
    url: "/process/{id}/"
    action: delete
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this process.
process-definitions:
  list:
    _type: link
    url: "/process-definitions/"
    action: get
  create:
    _type: link
    url: "/process-definitions/"
    action: post
    encoding: application/json
    fields:
    - name: object_ids
      location: form
      schema:
        _type: array
        title: Object ids
        description: ''
    - name: version
      required: true
      location: form
      schema:
        _type: string
        title: Version
        description: ''
    - name: name
      required: true
      location: form
      schema:
        _type: string
        title: Name
        description: ''
    - name: slug
      required: true
      location: form
      schema:
        _type: string
        title: Slug
        description: ''
    - name: docs
      location: form
      schema:
        _type: string
        title: Docs
        description: Markdown is supported
    - name: example_payload
      location: form
      schema:
        _type: string
        title: Example payload
        description: ''
    - name: example_response
      location: form
      schema:
        _type: string
        title: Example response
        description: ''
    - name: is_live
      location: form
      schema:
        _type: boolean
        title: Is live
        description: Whether or not this process is publically available
  read:
    _type: link
    url: "/process-definitions/{id}/"
    action: get
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this process definition.
  update:
    _type: link
    url: "/process-definitions/{id}/"
    action: put
    encoding: application/json
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this process definition.
    - name: object_ids
      location: form
      schema:
        _type: array
        title: Object ids
        description: ''
    - name: version
      required: true
      location: form
      schema:
        _type: string
        title: Version
        description: ''
    - name: name
      required: true
      location: form
      schema:
        _type: string
        title: Name
        description: ''
    - name: slug
      required: true
      location: form
      schema:
        _type: string
        title: Slug
        description: ''
    - name: docs
      location: form
      schema:
        _type: string
        title: Docs
        description: Markdown is supported
    - name: example_payload
      location: form
      schema:
        _type: string
        title: Example payload
        description: ''
    - name: example_response
      location: form
      schema:
        _type: string
        title: Example response
        description: ''
    - name: is_live
      location: form
      schema:
        _type: boolean
        title: Is live
        description: Whether or not this process is publically available
  partial_update:
    _type: link
    url: "/process-definitions/{id}/"
    action: patch
    encoding: application/json
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this process definition.
    - name: object_ids
      location: form
      schema:
        _type: array
        title: Object ids
        description: ''
    - name: version
      location: form
      schema:
        _type: string
        title: Version
        description: ''
    - name: name
      location: form
      schema:
        _type: string
        title: Name
        description: ''
    - name: slug
      location: form
      schema:
        _type: string
        title: Slug
        description: ''
    - name: docs
      location: form
      schema:
        _type: string
        title: Docs
        description: Markdown is supported
    - name: example_payload
      location: form
      schema:
        _type: string
        title: Example payload
        description: ''
    - name: example_response
      location: form
      schema:
        _type: string
        title: Example response
        description: ''
    - name: is_live
      location: form
      schema:
        _type: boolean
        title: Is live
        description: Whether or not this process is publically available
  delete:
    _type: link
    url: "/process-definitions/{id}/"
    action: delete
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this process definition.
registered-tasks:
  list:
    _type: link
    url: "/registered-tasks/"
    action: get
  create:
    _type: link
    url: "/registered-tasks/"
    action: post
    encoding: application/json
    fields:
    - name: service
      location: form
      schema:
        _type: string
        title: Service
        description: This is downstream service to call
    - name: name
      location: form
      schema:
        _type: string
        title: Name
        description: This is the formal name of the test that will be called
    - name: friendly_name
      location: form
      schema:
        _type: string
        title: Friendly name
        description: ''
    - name: registered_runners
      location: form
      schema:
        _type: array
        title: Registered runners
        description: A list of the runners available for this task
    - name: production_status
      location: form
      schema:
        _type: enum
        title: Production status
        description: ''
        enum:
        - alpha
        - beta
        - stable
    - name: docs
      location: form
      schema:
        _type: string
        title: Docs
        description: Markdown is supported
    - name: example_payload
      location: form
      schema:
        _type: string
        title: Example payload
        description: ''
    - name: example_response
      location: form
      schema:
        _type: string
        title: Example response
        description: ''
  read:
    _type: link
    url: "/registered-tasks/{id}/"
    action: get
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this registered task.
  update:
    _type: link
    url: "/registered-tasks/{id}/"
    action: put
    encoding: application/json
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this registered task.
    - name: service
      location: form
      schema:
        _type: string
        title: Service
        description: This is downstream service to call
    - name: name
      location: form
      schema:
        _type: string
        title: Name
        description: This is the formal name of the test that will be called
    - name: friendly_name
      location: form
      schema:
        _type: string
        title: Friendly name
        description: ''
    - name: registered_runners
      location: form
      schema:
        _type: array
        title: Registered runners
        description: A list of the runners available for this task
    - name: production_status
      location: form
      schema:
        _type: enum
        title: Production status
        description: ''
        enum:
        - alpha
        - beta
        - stable
    - name: docs
      location: form
      schema:
        _type: string
        title: Docs
        description: Markdown is supported
    - name: example_payload
      location: form
      schema:
        _type: string
        title: Example payload
        description: ''
    - name: example_response
      location: form
      schema:
        _type: string
        title: Example response
        description: ''
  partial_update:
    _type: link
    url: "/registered-tasks/{id}/"
    action: patch
    encoding: application/json
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this registered task.
    - name: service
      location: form
      schema:
        _type: string
        title: Service
        description: This is downstream service to call
    - name: name
      location: form
      schema:
        _type: string
        title: Name
        description: This is the formal name of the test that will be called
    - name: friendly_name
      location: form
      schema:
        _type: string
        title: Friendly name
        description: ''
    - name: registered_runners
      location: form
      schema:
        _type: array
        title: Registered runners
        description: A list of the runners available for this task
    - name: production_status
      location: form
      schema:
        _type: enum
        title: Production status
        description: ''
        enum:
        - alpha
        - beta
        - stable
    - name: docs
      location: form
      schema:
        _type: string
        title: Docs
        description: Markdown is supported
    - name: example_payload
      location: form
      schema:
        _type: string
        title: Example payload
        description: ''
    - name: example_response
      location: form
      schema:
        _type: string
        title: Example response
        description: ''
  delete:
    _type: link
    url: "/registered-tasks/{id}/"
    action: delete
    fields:
    - name: id
      required: true
      location: path
      schema:
        _type: integer
        title: ID
        description: A unique integer value identifying this registered task.
tasks:
  list:
    _type: link
    url: "/tasks/"
    action: get
    description: |-
      Viewset for upstream microservices which exposes tasks
      over API (not intended to be available outside the internal network)
  create:
    _type: link
    url: "/tasks/"
    action: post
    description: |-
      Create a task

      POST /task/:method/ --data payload

