# Generated by Django 2.0 on 2018-06-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180610_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='runner',
            field=models.CharField(choices=[('api.tasks.http_task_runner', 'Trigger a task over HTTP'), ('api.tasks.local_task_runner', 'Call a locally available task')], max_length=50),
        ),
    ]
