# Generated by Django 2.0 on 2018-06-13 15:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180610_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredtask',
            name='docs',
            field=models.TextField(blank=True, help_text='Markdown is supported', null=True),
        ),
        migrations.AddField(
            model_name='registeredtask',
            name='example_payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='registeredtask',
            name='example_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='processdefinition',
            name='example_payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='processdefinition',
            name='example_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
