# Generated by Django 2.0 on 2018-06-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180615_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ProcessTask'),
        ),
    ]
