# Generated by Django 2.0 on 2018-06-22 07:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180618_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processtask',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='schedule_offset_from_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, db_index=True, default=[], help_text='A tuple in the format: ["payload.object.date_created", "60"]', null=True, size=None),
        ),
    ]
