# Generated by Django 2.0 on 2018-06-22 10:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180622_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdefinition',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Define what the payload should look like using a jsonschema. If provided, this will be used for validation', null=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='payload_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='A jinja/django template which will be parsed with the context from the parent process to create the payload for the task to be run', null=True),
        ),
    ]
