# Generated by Django 2.0 on 2018-06-22 11:43

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180622_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='actor',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='object_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, db_index=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='process',
            name='owners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, db_index=True, default=[], help_text='object keys for objects that are allowed to act on this process', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='process',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
